name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup QPM
        uses: fernthedev/qpm-action@v1
        with:
          restore: true
          cache: false

      - name: Restore dependencies
        run: qpm restore

      - name: Build QMOD
        run: qpm s qmod

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BSCamera
          path: ./*.qmod
