name: Build

env:
  module_id: practicereplaywatcher
  qmodName: PracticeReplayWatcher

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Create ndkpath.txt
        run: |
          echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt
          cat ${GITHUB_WORKSPACE}/ndkpath.txt

      - name: Restore QPM dependencies
        uses: Fernthedev/qpm-action@v1
        with:
          workflow_token: ${{ secrets.GITHUB_TOKEN }}
          restore: true
          resolve_ndk: true
          cache: false

      - name: Clean build folder
        run: rm -rf ${GITHUB_WORKSPACE}/build

      - name: Build mod
        run: |
          cd ${GITHUB_WORKSPACE}
          qpm restore
          qpm s qmod

      - name: Upload qmod artifact
        uses: actions/upload-artifact@v4
        with:
          name: PracticeReplayWatcher.qmod
          path: ./*.qmod
          if-no-files-found: error
