name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install QPM
        uses: Fernthedev/qpm-action@main
        with:
          workflow_token: ${{ secrets.GITHUB_TOKEN }}
          restore: true
          cache: true

      - name: Build
        run: |
          cd ${{ github.workspace }}
          qpm s build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: |
            ./build/*.so
            ./build/debug/*.so
